CREATE TABLE IF NOT EXISTS forges (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS forge_members (
    id VARCHAR(255) PRIMARY KEY,
    forge_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
);