[package]
name = "guildhall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
salvo = "0.63.0"
shuttle-salvo = "0.43.0"
shuttle-runtime = "0.43.0"
tokio = "1.26.0"