[tasks.init_web]
script = "mkdir -p static && git submodule update --init --recursive"

[tasks.build_web]
dependencies = ["init_web"]
cwd = "./guildhall_web"
script = "flutter build web"

[tasks.copy_web]
dependencies = ["build_web"]
script = "cp -r guildhall_web/build/web/* static/"

[tasks.web]
dependencies = ["copy_web"]
watch = {postpone=true, watch= ["./guildhall_web/lib"]}

[tasks.api]
command = "cargo"
args = ["run"]
watch = {watch = ["./src"]}

[tasks.run]
run_task = { name = ["web", "api"], fork = true, parallel = true }
